"""
生成完整的高校种子数据 — 基于真实高校名单

数据来源：教育部公布的全国高等学校名单（截至2024年）
包含：985/211/双一流/普通本科/专科 院校
"""

import json
import os

# ============================================================
# 985 高校（39所）
# ============================================================
SCHOOLS_985 = [
    {
        "name": "北京大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "综合",
        "ranking": 1,
    },
    {
        "name": "清华大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "理工",
        "ranking": 2,
    },
    {
        "name": "复旦大学",
        "province": "上海",
        "city": "上海",
        "level": "985",
        "school_type": "综合",
        "ranking": 3,
    },
    {
        "name": "上海交通大学",
        "province": "上海",
        "city": "上海",
        "level": "985",
        "school_type": "理工",
        "ranking": 4,
    },
    {
        "name": "浙江大学",
        "province": "浙江",
        "city": "杭州",
        "level": "985",
        "school_type": "综合",
        "ranking": 5,
    },
    {
        "name": "中国科学技术大学",
        "province": "安徽",
        "city": "合肥",
        "level": "985",
        "school_type": "理工",
        "ranking": 6,
    },
    {
        "name": "南京大学",
        "province": "江苏",
        "city": "南京",
        "level": "985",
        "school_type": "综合",
        "ranking": 7,
    },
    {
        "name": "武汉大学",
        "province": "湖北",
        "city": "武汉",
        "level": "985",
        "school_type": "综合",
        "ranking": 8,
    },
    {
        "name": "华中科技大学",
        "province": "湖北",
        "city": "武汉",
        "level": "985",
        "school_type": "理工",
        "ranking": 9,
    },
    {
        "name": "中山大学",
        "province": "广东",
        "city": "广州",
        "level": "985",
        "school_type": "综合",
        "ranking": 10,
    },
    {
        "name": "哈尔滨工业大学",
        "province": "黑龙江",
        "city": "哈尔滨",
        "level": "985",
        "school_type": "理工",
        "ranking": 11,
    },
    {
        "name": "西安交通大学",
        "province": "陕西",
        "city": "西安",
        "level": "985",
        "school_type": "理工",
        "ranking": 12,
    },
    {
        "name": "北京师范大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "师范",
        "ranking": 13,
    },
    {
        "name": "四川大学",
        "province": "四川",
        "city": "成都",
        "level": "985",
        "school_type": "综合",
        "ranking": 14,
    },
    {
        "name": "同济大学",
        "province": "上海",
        "city": "上海",
        "level": "985",
        "school_type": "理工",
        "ranking": 15,
    },
    {
        "name": "中南大学",
        "province": "湖南",
        "city": "长沙",
        "level": "985",
        "school_type": "综合",
        "ranking": 16,
    },
    {
        "name": "山东大学",
        "province": "山东",
        "city": "济南",
        "level": "985",
        "school_type": "综合",
        "ranking": 17,
    },
    {
        "name": "厦门大学",
        "province": "福建",
        "city": "厦门",
        "level": "985",
        "school_type": "综合",
        "ranking": 18,
    },
    {
        "name": "东南大学",
        "province": "江苏",
        "city": "南京",
        "level": "985",
        "school_type": "理工",
        "ranking": 19,
    },
    {
        "name": "天津大学",
        "province": "天津",
        "city": "天津",
        "level": "985",
        "school_type": "理工",
        "ranking": 20,
    },
    {
        "name": "北京航空航天大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "理工",
        "ranking": 21,
    },
    {
        "name": "北京理工大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "理工",
        "ranking": 22,
    },
    {
        "name": "大连理工大学",
        "province": "辽宁",
        "city": "大连",
        "level": "985",
        "school_type": "理工",
        "ranking": 23,
    },
    {
        "name": "吉林大学",
        "province": "吉林",
        "city": "长春",
        "level": "985",
        "school_type": "综合",
        "ranking": 24,
    },
    {
        "name": "南开大学",
        "province": "天津",
        "city": "天津",
        "level": "985",
        "school_type": "综合",
        "ranking": 25,
    },
    {
        "name": "华南理工大学",
        "province": "广东",
        "city": "广州",
        "level": "985",
        "school_type": "理工",
        "ranking": 26,
    },
    {
        "name": "重庆大学",
        "province": "重庆",
        "city": "重庆",
        "level": "985",
        "school_type": "综合",
        "ranking": 27,
    },
    {
        "name": "电子科技大学",
        "province": "四川",
        "city": "成都",
        "level": "985",
        "school_type": "理工",
        "ranking": 28,
    },
    {
        "name": "西北工业大学",
        "province": "陕西",
        "city": "西安",
        "level": "985",
        "school_type": "理工",
        "ranking": 29,
    },
    {
        "name": "兰州大学",
        "province": "甘肃",
        "city": "兰州",
        "level": "985",
        "school_type": "综合",
        "ranking": 30,
    },
    {
        "name": "中国农业大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "农林",
        "ranking": 31,
    },
    {
        "name": "中国海洋大学",
        "province": "山东",
        "city": "青岛",
        "level": "985",
        "school_type": "综合",
        "ranking": 32,
    },
    {
        "name": "中央民族大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "民族",
        "ranking": 33,
    },
    {
        "name": "湖南大学",
        "province": "湖南",
        "city": "长沙",
        "level": "985",
        "school_type": "综合",
        "ranking": 34,
    },
    {
        "name": "华东师范大学",
        "province": "上海",
        "city": "上海",
        "level": "985",
        "school_type": "师范",
        "ranking": 35,
    },
    {
        "name": "中国人民大学",
        "province": "北京",
        "city": "北京",
        "level": "985",
        "school_type": "综合",
        "ranking": 36,
    },
    {
        "name": "国防科技大学",
        "province": "湖南",
        "city": "长沙",
        "level": "985",
        "school_type": "军事",
        "ranking": 37,
    },
    {
        "name": "西北农林科技大学",
        "province": "陕西",
        "city": "杨凌",
        "level": "985",
        "school_type": "农林",
        "ranking": 38,
    },
    {
        "name": "东北大学",
        "province": "辽宁",
        "city": "沈阳",
        "level": "985",
        "school_type": "理工",
        "ranking": 39,
    },
]

# ============================================================
# 211 高校（非985，约76所）
# ============================================================
SCHOOLS_211 = [
    {
        "name": "北京交通大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "理工",
        "ranking": 40,
    },
    {
        "name": "北京工业大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "理工",
        "ranking": 41,
    },
    {
        "name": "北京科技大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "理工",
        "ranking": 42,
    },
    {
        "name": "北京化工大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "理工",
        "ranking": 43,
    },
    {
        "name": "北京邮电大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "理工",
        "ranking": 44,
    },
    {
        "name": "北京林业大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "农林",
        "ranking": 45,
    },
    {
        "name": "北京中医药大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "医药",
        "ranking": 46,
    },
    {
        "name": "对外经济贸易大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "财经",
        "ranking": 47,
    },
    {
        "name": "中央财经大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "财经",
        "ranking": 48,
    },
    {
        "name": "中国政法大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "政法",
        "ranking": 49,
    },
    {
        "name": "华北电力大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "理工",
        "ranking": 50,
    },
    {
        "name": "中国矿业大学",
        "province": "江苏",
        "city": "徐州",
        "level": "211",
        "school_type": "理工",
        "ranking": 51,
    },
    {
        "name": "中国石油大学",
        "province": "山东",
        "city": "青岛",
        "level": "211",
        "school_type": "理工",
        "ranking": 52,
    },
    {
        "name": "中国地质大学",
        "province": "湖北",
        "city": "武汉",
        "level": "211",
        "school_type": "理工",
        "ranking": 53,
    },
    {
        "name": "上海财经大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "财经",
        "ranking": 54,
    },
    {
        "name": "上海大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "综合",
        "ranking": 55,
    },
    {
        "name": "华东理工大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "理工",
        "ranking": 56,
    },
    {
        "name": "东华大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "理工",
        "ranking": 57,
    },
    {
        "name": "上海外国语大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "语言",
        "ranking": 58,
    },
    {
        "name": "第二军医大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "军事",
        "ranking": 59,
    },
    {
        "name": "苏州大学",
        "province": "江苏",
        "city": "苏州",
        "level": "211",
        "school_type": "综合",
        "ranking": 60,
    },
    {
        "name": "南京师范大学",
        "province": "江苏",
        "city": "南京",
        "level": "211",
        "school_type": "师范",
        "ranking": 61,
    },
    {
        "name": "南京航空航天大学",
        "province": "江苏",
        "city": "南京",
        "level": "211",
        "school_type": "理工",
        "ranking": 62,
    },
    {
        "name": "南京理工大学",
        "province": "江苏",
        "city": "南京",
        "level": "211",
        "school_type": "理工",
        "ranking": 63,
    },
    {
        "name": "河海大学",
        "province": "江苏",
        "city": "南京",
        "level": "211",
        "school_type": "理工",
        "ranking": 64,
    },
    {
        "name": "江南大学",
        "province": "江苏",
        "city": "无锡",
        "level": "211",
        "school_type": "综合",
        "ranking": 65,
    },
    {
        "name": "南京农业大学",
        "province": "江苏",
        "city": "南京",
        "level": "211",
        "school_type": "农林",
        "ranking": 66,
    },
    {
        "name": "中国药科大学",
        "province": "江苏",
        "city": "南京",
        "level": "211",
        "school_type": "医药",
        "ranking": 67,
    },
    {
        "name": "安徽大学",
        "province": "安徽",
        "city": "合肥",
        "level": "211",
        "school_type": "综合",
        "ranking": 68,
    },
    {
        "name": "合肥工业大学",
        "province": "安徽",
        "city": "合肥",
        "level": "211",
        "school_type": "理工",
        "ranking": 69,
    },
    {
        "name": "福州大学",
        "province": "福建",
        "city": "福州",
        "level": "211",
        "school_type": "理工",
        "ranking": 70,
    },
    {
        "name": "南昌大学",
        "province": "江西",
        "city": "南昌",
        "level": "211",
        "school_type": "综合",
        "ranking": 71,
    },
    {
        "name": "郑州大学",
        "province": "河南",
        "city": "郑州",
        "level": "211",
        "school_type": "综合",
        "ranking": 72,
    },
    {
        "name": "武汉理工大学",
        "province": "湖北",
        "city": "武汉",
        "level": "211",
        "school_type": "理工",
        "ranking": 73,
    },
    {
        "name": "华中农业大学",
        "province": "湖北",
        "city": "武汉",
        "level": "211",
        "school_type": "农林",
        "ranking": 74,
    },
    {
        "name": "华中师范大学",
        "province": "湖北",
        "city": "武汉",
        "level": "211",
        "school_type": "师范",
        "ranking": 75,
    },
    {
        "name": "中南财经政法大学",
        "province": "湖北",
        "city": "武汉",
        "level": "211",
        "school_type": "财经",
        "ranking": 76,
    },
    {
        "name": "湖南师范大学",
        "province": "湖南",
        "city": "长沙",
        "level": "211",
        "school_type": "师范",
        "ranking": 77,
    },
    {
        "name": "暨南大学",
        "province": "广东",
        "city": "广州",
        "level": "211",
        "school_type": "综合",
        "ranking": 78,
    },
    {
        "name": "华南师范大学",
        "province": "广东",
        "city": "广州",
        "level": "211",
        "school_type": "师范",
        "ranking": 79,
    },
    {
        "name": "广西大学",
        "province": "广西",
        "city": "南宁",
        "level": "211",
        "school_type": "综合",
        "ranking": 80,
    },
    {
        "name": "海南大学",
        "province": "海南",
        "city": "海口",
        "level": "211",
        "school_type": "综合",
        "ranking": 81,
    },
    {
        "name": "四川农业大学",
        "province": "四川",
        "city": "雅安",
        "level": "211",
        "school_type": "农林",
        "ranking": 82,
    },
    {
        "name": "西南交通大学",
        "province": "四川",
        "city": "成都",
        "level": "211",
        "school_type": "理工",
        "ranking": 83,
    },
    {
        "name": "西南财经大学",
        "province": "四川",
        "city": "成都",
        "level": "211",
        "school_type": "财经",
        "ranking": 84,
    },
    {
        "name": "贵州大学",
        "province": "贵州",
        "city": "贵阳",
        "level": "211",
        "school_type": "综合",
        "ranking": 85,
    },
    {
        "name": "云南大学",
        "province": "云南",
        "city": "昆明",
        "level": "211",
        "school_type": "综合",
        "ranking": 86,
    },
    {
        "name": "西北大学",
        "province": "陕西",
        "city": "西安",
        "level": "211",
        "school_type": "综合",
        "ranking": 87,
    },
    {
        "name": "西安电子科技大学",
        "province": "陕西",
        "city": "西安",
        "level": "211",
        "school_type": "理工",
        "ranking": 88,
    },
    {
        "name": "长安大学",
        "province": "陕西",
        "city": "西安",
        "level": "211",
        "school_type": "理工",
        "ranking": 89,
    },
    {
        "name": "陕西师范大学",
        "province": "陕西",
        "city": "西安",
        "level": "211",
        "school_type": "师范",
        "ranking": 90,
    },
    {
        "name": "第四军医大学",
        "province": "陕西",
        "city": "西安",
        "level": "211",
        "school_type": "军事",
        "ranking": 91,
    },
    {
        "name": "宁夏大学",
        "province": "宁夏",
        "city": "银川",
        "level": "211",
        "school_type": "综合",
        "ranking": 92,
    },
    {
        "name": "新疆大学",
        "province": "新疆",
        "city": "乌鲁木齐",
        "level": "211",
        "school_type": "综合",
        "ranking": 93,
    },
    {
        "name": "青海大学",
        "province": "青海",
        "city": "西宁",
        "level": "211",
        "school_type": "综合",
        "ranking": 94,
    },
    {
        "name": "西藏大学",
        "province": "西藏",
        "city": "拉萨",
        "level": "211",
        "school_type": "综合",
        "ranking": 95,
    },
    {
        "name": "太原理工大学",
        "province": "山西",
        "city": "太原",
        "level": "211",
        "school_type": "理工",
        "ranking": 96,
    },
    {
        "name": "内蒙古大学",
        "province": "内蒙古",
        "city": "呼和浩特",
        "level": "211",
        "school_type": "综合",
        "ranking": 97,
    },
    {
        "name": "东北师范大学",
        "province": "吉林",
        "city": "长春",
        "level": "211",
        "school_type": "师范",
        "ranking": 98,
    },
    {
        "name": "延边大学",
        "province": "吉林",
        "city": "延吉",
        "level": "211",
        "school_type": "综合",
        "ranking": 99,
    },
    {
        "name": "东北农业大学",
        "province": "黑龙江",
        "city": "哈尔滨",
        "level": "211",
        "school_type": "农林",
        "ranking": 100,
    },
    {
        "name": "东北林业大学",
        "province": "黑龙江",
        "city": "哈尔滨",
        "level": "211",
        "school_type": "农林",
        "ranking": 101,
    },
    {
        "name": "哈尔滨工程大学",
        "province": "黑龙江",
        "city": "哈尔滨",
        "level": "211",
        "school_type": "理工",
        "ranking": 102,
    },
    {
        "name": "辽宁大学",
        "province": "辽宁",
        "city": "沈阳",
        "level": "211",
        "school_type": "综合",
        "ranking": 103,
    },
    {
        "name": "大连海事大学",
        "province": "辽宁",
        "city": "大连",
        "level": "211",
        "school_type": "理工",
        "ranking": 104,
    },
    {
        "name": "河北工业大学",
        "province": "河北",
        "city": "天津",
        "level": "211",
        "school_type": "理工",
        "ranking": 105,
    },
    {
        "name": "天津医科大学",
        "province": "天津",
        "city": "天津",
        "level": "211",
        "school_type": "医药",
        "ranking": 106,
    },
    {
        "name": "北京外国语大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "语言",
        "ranking": 107,
    },
    {
        "name": "北京体育大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "体育",
        "ranking": 108,
    },
    {
        "name": "中央音乐学院",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "艺术",
        "ranking": 109,
    },
    {
        "name": "北京协和医学院",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "医药",
        "ranking": 110,
    },
    {
        "name": "中国传媒大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "语言",
        "ranking": 111,
    },
    {
        "name": "北京中医药大学",
        "province": "北京",
        "city": "北京",
        "level": "211",
        "school_type": "医药",
        "ranking": 112,
    },
    {
        "name": "上海中医药大学",
        "province": "上海",
        "city": "上海",
        "level": "211",
        "school_type": "医药",
        "ranking": 113,
    },
    {
        "name": "南京邮电大学",
        "province": "江苏",
        "city": "南京",
        "level": "双一流",
        "school_type": "理工",
        "ranking": 114,
    },
    {
        "name": "南京信息工程大学",
        "province": "江苏",
        "city": "南京",
        "level": "双一流",
        "school_type": "理工",
        "ranking": 115,
    },
    {
        "name": "宁波大学",
        "province": "浙江",
        "city": "宁波",
        "level": "双一流",
        "school_type": "综合",
        "ranking": 116,
    },
    {
        "name": "中国美术学院",
        "province": "浙江",
        "city": "杭州",
        "level": "双一流",
        "school_type": "艺术",
        "ranking": 117,
    },
]

# ============================================================
# 知名普通本科（按省份分布，约200所）
# ============================================================
SCHOOLS_NORMAL = [
    # 北京
    {
        "name": "首都师范大学",
        "province": "北京",
        "city": "北京",
        "level": "普通",
        "school_type": "师范",
        "ranking": 118,
    },
    {
        "name": "首都医科大学",
        "province": "北京",
        "city": "北京",
        "level": "普通",
        "school_type": "医药",
        "ranking": 119,
    },
    {
        "name": "北京语言大学",
        "province": "北京",
        "city": "北京",
        "level": "普通",
        "school_type": "语言",
        "ranking": 120,
    },
    {
        "name": "北京工商大学",
        "province": "北京",
        "city": "北京",
        "level": "普通",
        "school_type": "财经",
        "ranking": 121,
    },
    {
        "name": "北京建筑大学",
        "province": "北京",
        "city": "北京",
        "level": "普通",
        "school_type": "理工",
        "ranking": 122,
    },
    # 上海
    {
        "name": "上海师范大学",
        "province": "上海",
        "city": "上海",
        "level": "普通",
        "school_type": "师范",
        "ranking": 123,
    },
    {
        "name": "上海理工大学",
        "province": "上海",
        "city": "上海",
        "level": "普通",
        "school_type": "理工",
        "ranking": 124,
    },
    {
        "name": "上海海事大学",
        "province": "上海",
        "city": "上海",
        "level": "普通",
        "school_type": "理工",
        "ranking": 125,
    },
    {
        "name": "华东政法大学",
        "province": "上海",
        "city": "上海",
        "level": "普通",
        "school_type": "政法",
        "ranking": 126,
    },
    {
        "name": "上海对外经贸大学",
        "province": "上海",
        "city": "上海",
        "level": "普通",
        "school_type": "财经",
        "ranking": 127,
    },
    # 江苏
    {
        "name": "扬州大学",
        "province": "江苏",
        "city": "扬州",
        "level": "普通",
        "school_type": "综合",
        "ranking": 128,
    },
    {
        "name": "江苏大学",
        "province": "江苏",
        "city": "镇江",
        "level": "普通",
        "school_type": "综合",
        "ranking": 129,
    },
    {
        "name": "南京工业大学",
        "province": "江苏",
        "city": "南京",
        "level": "普通",
        "school_type": "理工",
        "ranking": 130,
    },
    {
        "name": "南京医科大学",
        "province": "江苏",
        "city": "南京",
        "level": "普通",
        "school_type": "医药",
        "ranking": 131,
    },
    {
        "name": "南京林业大学",
        "province": "江苏",
        "city": "南京",
        "level": "普通",
        "school_type": "农林",
        "ranking": 132,
    },
    # 浙江
    {
        "name": "浙江工业大学",
        "province": "浙江",
        "city": "杭州",
        "level": "普通",
        "school_type": "理工",
        "ranking": 133,
    },
    {
        "name": "浙江师范大学",
        "province": "浙江",
        "city": "金华",
        "level": "普通",
        "school_type": "师范",
        "ranking": 134,
    },
    {
        "name": "杭州电子科技大学",
        "province": "浙江",
        "city": "杭州",
        "level": "普通",
        "school_type": "理工",
        "ranking": 135,
    },
    {
        "name": "浙江工商大学",
        "province": "浙江",
        "city": "杭州",
        "level": "普通",
        "school_type": "财经",
        "ranking": 136,
    },
    {
        "name": "温州医科大学",
        "province": "浙江",
        "city": "温州",
        "level": "普通",
        "school_type": "医药",
        "ranking": 137,
    },
    # 广东
    {
        "name": "深圳大学",
        "province": "广东",
        "city": "深圳",
        "level": "普通",
        "school_type": "综合",
        "ranking": 138,
    },
    {
        "name": "广东工业大学",
        "province": "广东",
        "city": "广州",
        "level": "普通",
        "school_type": "理工",
        "ranking": 139,
    },
    {
        "name": "华南农业大学",
        "province": "广东",
        "city": "广州",
        "level": "普通",
        "school_type": "农林",
        "ranking": 140,
    },
    {
        "name": "南方医科大学",
        "province": "广东",
        "city": "广州",
        "level": "普通",
        "school_type": "医药",
        "ranking": 141,
    },
    {
        "name": "广州大学",
        "province": "广东",
        "city": "广州",
        "level": "普通",
        "school_type": "综合",
        "ranking": 142,
    },
    {
        "name": "汕头大学",
        "province": "广东",
        "city": "汕头",
        "level": "普通",
        "school_type": "综合",
        "ranking": 143,
    },
    # 湖北
    {
        "name": "武汉科技大学",
        "province": "湖北",
        "city": "武汉",
        "level": "普通",
        "school_type": "理工",
        "ranking": 144,
    },
    {
        "name": "湖北大学",
        "province": "湖北",
        "city": "武汉",
        "level": "普通",
        "school_type": "综合",
        "ranking": 145,
    },
    {
        "name": "中南民族大学",
        "province": "湖北",
        "city": "武汉",
        "level": "普通",
        "school_type": "民族",
        "ranking": 146,
    },
    # 湖南
    {
        "name": "湘潭大学",
        "province": "湖南",
        "city": "湘潭",
        "level": "普通",
        "school_type": "综合",
        "ranking": 147,
    },
    {
        "name": "长沙理工大学",
        "province": "湖南",
        "city": "长沙",
        "level": "普通",
        "school_type": "理工",
        "ranking": 148,
    },
    {
        "name": "湖南农业大学",
        "province": "湖南",
        "city": "长沙",
        "level": "普通",
        "school_type": "农林",
        "ranking": 149,
    },
    # 四川
    {
        "name": "成都理工大学",
        "province": "四川",
        "city": "成都",
        "level": "普通",
        "school_type": "理工",
        "ranking": 150,
    },
    {
        "name": "西南石油大学",
        "province": "四川",
        "city": "成都",
        "level": "普通",
        "school_type": "理工",
        "ranking": 151,
    },
    {
        "name": "四川师范大学",
        "province": "四川",
        "city": "成都",
        "level": "普通",
        "school_type": "师范",
        "ranking": 152,
    },
    {
        "name": "成都中医药大学",
        "province": "四川",
        "city": "成都",
        "level": "普通",
        "school_type": "医药",
        "ranking": 153,
    },
    # 重庆
    {
        "name": "西南大学",
        "province": "重庆",
        "city": "重庆",
        "level": "普通",
        "school_type": "综合",
        "ranking": 154,
    },
    {
        "name": "重庆医科大学",
        "province": "重庆",
        "city": "重庆",
        "level": "普通",
        "school_type": "医药",
        "ranking": 155,
    },
    {
        "name": "重庆邮电大学",
        "province": "重庆",
        "city": "重庆",
        "level": "普通",
        "school_type": "理工",
        "ranking": 156,
    },
    # 山东
    {
        "name": "中国石油大学(华东)",
        "province": "山东",
        "city": "青岛",
        "level": "普通",
        "school_type": "理工",
        "ranking": 157,
    },
    {
        "name": "青岛大学",
        "province": "山东",
        "city": "青岛",
        "level": "普通",
        "school_type": "综合",
        "ranking": 158,
    },
    {
        "name": "山东师范大学",
        "province": "山东",
        "city": "济南",
        "level": "普通",
        "school_type": "师范",
        "ranking": 159,
    },
    {
        "name": "济南大学",
        "province": "山东",
        "city": "济南",
        "level": "普通",
        "school_type": "综合",
        "ranking": 160,
    },
    # 河南
    {
        "name": "河南大学",
        "province": "河南",
        "city": "开封",
        "level": "普通",
        "school_type": "综合",
        "ranking": 161,
    },
    {
        "name": "河南师范大学",
        "province": "河南",
        "city": "新乡",
        "level": "普通",
        "school_type": "师范",
        "ranking": 162,
    },
    {
        "name": "河南农业大学",
        "province": "河南",
        "city": "郑州",
        "level": "普通",
        "school_type": "农林",
        "ranking": 163,
    },
    # 河北
    {
        "name": "燕山大学",
        "province": "河北",
        "city": "秦皇岛",
        "level": "普通",
        "school_type": "理工",
        "ranking": 164,
    },
    {
        "name": "河北大学",
        "province": "河北",
        "city": "保定",
        "level": "普通",
        "school_type": "综合",
        "ranking": 165,
    },
    {
        "name": "石家庄铁道大学",
        "province": "河北",
        "city": "石家庄",
        "level": "普通",
        "school_type": "理工",
        "ranking": 166,
    },
    # 辽宁
    {
        "name": "东北财经大学",
        "province": "辽宁",
        "city": "大连",
        "level": "普通",
        "school_type": "财经",
        "ranking": 167,
    },
    {
        "name": "大连医科大学",
        "province": "辽宁",
        "city": "大连",
        "level": "普通",
        "school_type": "医药",
        "ranking": 168,
    },
    {
        "name": "沈阳建筑大学",
        "province": "辽宁",
        "city": "沈阳",
        "level": "普通",
        "school_type": "理工",
        "ranking": 169,
    },
    # 吉林
    {
        "name": "长春理工大学",
        "province": "吉林",
        "city": "长春",
        "level": "普通",
        "school_type": "理工",
        "ranking": 170,
    },
    {
        "name": "东北电力大学",
        "province": "吉林",
        "city": "吉林",
        "level": "普通",
        "school_type": "理工",
        "ranking": 171,
    },
    # 黑龙江
    {
        "name": "黑龙江大学",
        "province": "黑龙江",
        "city": "哈尔滨",
        "level": "普通",
        "school_type": "综合",
        "ranking": 172,
    },
    {
        "name": "哈尔滨医科大学",
        "province": "黑龙江",
        "city": "哈尔滨",
        "level": "普通",
        "school_type": "医药",
        "ranking": 173,
    },
    # 陕西
    {
        "name": "西安建筑科技大学",
        "province": "陕西",
        "city": "西安",
        "level": "普通",
        "school_type": "理工",
        "ranking": 174,
    },
    {
        "name": "西安理工大学",
        "province": "陕西",
        "city": "西安",
        "level": "普通",
        "school_type": "理工",
        "ranking": 175,
    },
    {
        "name": "陕西科技大学",
        "province": "陕西",
        "city": "西安",
        "level": "普通",
        "school_type": "理工",
        "ranking": 176,
    },
    # 福建
    {
        "name": "福建师范大学",
        "province": "福建",
        "city": "福州",
        "level": "普通",
        "school_type": "师范",
        "ranking": 177,
    },
    {
        "name": "华侨大学",
        "province": "福建",
        "city": "泉州",
        "level": "普通",
        "school_type": "综合",
        "ranking": 178,
    },
    {
        "name": "集美大学",
        "province": "福建",
        "city": "厦门",
        "level": "普通",
        "school_type": "综合",
        "ranking": 179,
    },
    # 江西
    {
        "name": "江西财经大学",
        "province": "江西",
        "city": "南昌",
        "level": "普通",
        "school_type": "财经",
        "ranking": 180,
    },
    {
        "name": "华东交通大学",
        "province": "江西",
        "city": "南昌",
        "level": "普通",
        "school_type": "理工",
        "ranking": 181,
    },
    # 甘肃
    {
        "name": "兰州交通大学",
        "province": "甘肃",
        "city": "兰州",
        "level": "普通",
        "school_type": "理工",
        "ranking": 182,
    },
    {
        "name": "兰州理工大学",
        "province": "甘肃",
        "city": "兰州",
        "level": "普通",
        "school_type": "理工",
        "ranking": 183,
    },
    # 云南
    {
        "name": "昆明理工大学",
        "province": "云南",
        "city": "昆明",
        "level": "普通",
        "school_type": "理工",
        "ranking": 184,
    },
    {
        "name": "云南师范大学",
        "province": "云南",
        "city": "昆明",
        "level": "普通",
        "school_type": "师范",
        "ranking": 185,
    },
    # 贵州
    {
        "name": "贵州师范大学",
        "province": "贵州",
        "city": "贵阳",
        "level": "普通",
        "school_type": "师范",
        "ranking": 186,
    },
    # 广西
    {
        "name": "广西师范大学",
        "province": "广西",
        "city": "桂林",
        "level": "普通",
        "school_type": "师范",
        "ranking": 187,
    },
    {
        "name": "桂林电子科技大学",
        "province": "广西",
        "city": "桂林",
        "level": "普通",
        "school_type": "理工",
        "ranking": 188,
    },
    # 山西
    {
        "name": "山西大学",
        "province": "山西",
        "city": "太原",
        "level": "普通",
        "school_type": "综合",
        "ranking": 189,
    },
    {
        "name": "中北大学",
        "province": "山西",
        "city": "太原",
        "level": "普通",
        "school_type": "理工",
        "ranking": 190,
    },
    # 内蒙古
    {
        "name": "内蒙古工业大学",
        "province": "内蒙古",
        "city": "呼和浩特",
        "level": "普通",
        "school_type": "理工",
        "ranking": 191,
    },
    {
        "name": "内蒙古农业大学",
        "province": "内蒙古",
        "city": "呼和浩特",
        "level": "普通",
        "school_type": "农林",
        "ranking": 192,
    },
    # 新疆
    {
        "name": "新疆医科大学",
        "province": "新疆",
        "city": "乌鲁木齐",
        "level": "普通",
        "school_type": "医药",
        "ranking": 193,
    },
    {
        "name": "石河子大学",
        "province": "新疆",
        "city": "石河子",
        "level": "普通",
        "school_type": "综合",
        "ranking": 194,
    },
    # 宁夏
    {
        "name": "宁夏医科大学",
        "province": "宁夏",
        "city": "银川",
        "level": "普通",
        "school_type": "医药",
        "ranking": 195,
    },
    # 海南
    {
        "name": "海南师范大学",
        "province": "海南",
        "city": "海口",
        "level": "普通",
        "school_type": "师范",
        "ranking": 196,
    },
    # 天津
    {
        "name": "天津师范大学",
        "province": "天津",
        "city": "天津",
        "level": "普通",
        "school_type": "师范",
        "ranking": 197,
    },
    {
        "name": "天津工业大学",
        "province": "天津",
        "city": "天津",
        "level": "普通",
        "school_type": "理工",
        "ranking": 198,
    },
    {
        "name": "天津财经大学",
        "province": "天津",
        "city": "天津",
        "level": "普通",
        "school_type": "财经",
        "ranking": 199,
    },
    {
        "name": "中国民航大学",
        "province": "天津",
        "city": "天津",
        "level": "普通",
        "school_type": "理工",
        "ranking": 200,
    },
]


def build_schools():
    """合并所有学校数据，标记 985/211/双一流，然后扩充到 3000+"""
    import random

    random.seed(42)

    base_schools = SCHOOLS_985 + SCHOOLS_211 + SCHOOLS_NORMAL
    existing_names = {s["name"] for s in base_schools}

    # 扩充数据：城市 + 类型组合生成更多院校
    CITIES = [
        # 直辖市 + 省会
        ("北京", "北京"),
        ("上海", "上海"),
        ("天津", "天津"),
        ("重庆", "重庆"),
        ("石家庄", "河北"),
        ("太原", "山西"),
        ("呼和浩特", "内蒙古"),
        ("沈阳", "辽宁"),
        ("长春", "吉林"),
        ("哈尔滨", "黑龙江"),
        ("南京", "江苏"),
        ("杭州", "浙江"),
        ("合肥", "安徽"),
        ("福州", "福建"),
        ("南昌", "江西"),
        ("济南", "山东"),
        ("郑州", "河南"),
        ("武汉", "湖北"),
        ("长沙", "湖南"),
        ("广州", "广东"),
        ("南宁", "广西"),
        ("海口", "海南"),
        ("成都", "四川"),
        ("贵阳", "贵州"),
        ("昆明", "云南"),
        ("拉萨", "西藏"),
        ("西安", "陕西"),
        ("兰州", "甘肃"),
        ("西宁", "青海"),
        ("银川", "宁夏"),
        ("乌鲁木齐", "新疆"),
        # 重要地级市
        ("大连", "辽宁"),
        ("鞍山", "辽宁"),
        ("抚顺", "辽宁"),
        ("锦州", "辽宁"),
        ("青岛", "山东"),
        ("烟台", "山东"),
        ("潍坊", "山东"),
        ("淄博", "山东"),
        ("济宁", "山东"),
        ("临沂", "山东"),
        ("威海", "山东"),
        ("泰安", "山东"),
        ("深圳", "广东"),
        ("珠海", "广东"),
        ("汕头", "广东"),
        ("佛山", "广东"),
        ("东莞", "广东"),
        ("中山", "广东"),
        ("惠州", "广东"),
        ("湛江", "广东"),
        ("厦门", "福建"),
        ("泉州", "福建"),
        ("漳州", "福建"),
        ("龙岩", "福建"),
        ("宁波", "浙江"),
        ("温州", "浙江"),
        ("嘉兴", "浙江"),
        ("湖州", "浙江"),
        ("绍兴", "浙江"),
        ("金华", "浙江"),
        ("台州", "浙江"),
        ("丽水", "浙江"),
        ("苏州", "江苏"),
        ("无锡", "江苏"),
        ("常州", "江苏"),
        ("南通", "江苏"),
        ("徐州", "江苏"),
        ("连云港", "江苏"),
        ("淮安", "江苏"),
        ("盐城", "江苏"),
        ("扬州", "江苏"),
        ("镇江", "江苏"),
        ("泰州", "江苏"),
        ("宿迁", "江苏"),
        ("洛阳", "河南"),
        ("开封", "河南"),
        ("新乡", "河南"),
        ("焦作", "河南"),
        ("许昌", "河南"),
        ("南阳", "河南"),
        ("信阳", "河南"),
        ("商丘", "河南"),
        ("襄阳", "湖北"),
        ("宜昌", "湖北"),
        ("荆州", "湖北"),
        ("黄冈", "湖北"),
        ("十堰", "湖北"),
        ("孝感", "湖北"),
        ("荆门", "湖北"),
        ("鄂州", "湖北"),
        ("岳阳", "湖南"),
        ("株洲", "湖南"),
        ("湘潭", "湖南"),
        ("衡阳", "湖南"),
        ("邵阳", "湖南"),
        ("常德", "湖南"),
        ("益阳", "湖南"),
        ("郴州", "湖南"),
        ("绵阳", "四川"),
        ("德阳", "四川"),
        ("宜宾", "四川"),
        ("泸州", "四川"),
        ("南充", "四川"),
        ("乐山", "四川"),
        ("内江", "四川"),
        ("自贡", "四川"),
        ("遵义", "贵州"),
        ("六盘水", "贵州"),
        ("安顺", "贵州"),
        ("毕节", "贵州"),
        ("曲靖", "云南"),
        ("大理", "云南"),
        ("玉溪", "云南"),
        ("红河", "云南"),
        ("咸阳", "陕西"),
        ("宝鸡", "陕西"),
        ("渭南", "陕西"),
        ("汉中", "陕西"),
        ("延安", "陕西"),
        ("榆林", "陕西"),
        ("安康", "陕西"),
        ("商洛", "陕西"),
        ("天水", "甘肃"),
        ("酒泉", "甘肃"),
        ("张掖", "甘肃"),
        ("武威", "甘肃"),
        ("保定", "河北"),
        ("唐山", "河北"),
        ("邯郸", "河北"),
        ("张家口", "河北"),
        ("承德", "河北"),
        ("廊坊", "河北"),
        ("沧州", "河北"),
        ("衡水", "河北"),
        ("大同", "山西"),
        ("临汾", "山西"),
        ("运城", "山西"),
        ("长治", "山西"),
        ("吉林", "吉林"),
        ("四平", "吉林"),
        ("通化", "吉林"),
        ("延边", "吉林"),
        ("齐齐哈尔", "黑龙江"),
        ("牡丹江", "黑龙江"),
        ("佳木斯", "黑龙江"),
        ("芜湖", "安徽"),
        ("蚌埠", "安徽"),
        ("马鞍山", "安徽"),
        ("安庆", "安徽"),
        ("九江", "江西"),
        ("赣州", "江西"),
        ("吉安", "江西"),
        ("上饶", "江西"),
        ("桂林", "广西"),
        ("柳州", "广西"),
        ("梧州", "广西"),
        ("北海", "广西"),
    ]

    TYPE_TEMPLATES = {
        "理工": [
            "工业大学",
            "理工大学",
            "工程学院",
            "科技学院",
            "信息工程学院",
            "机械工程学院",
            "电气工程学院",
        ],
        "师范": ["师范大学", "师范学院", "教育学院", "文理学院"],
        "综合": ["大学", "学院"],
        "医药": ["医科大学", "医学院", "中医药大学", "药学院", "护理学院"],
        "财经": ["财经大学", "经济学院", "工商学院", "商学院"],
        "农林": ["农业大学", "林业大学", "农林学院"],
        "政法": ["政法大学", "法学院"],
        "语言": ["外国语大学", "语言学院"],
        "艺术": ["艺术学院", "美术学院", "音乐学院", "设计学院"],
        "体育": ["体育学院", "体育大学"],
        "民族": ["民族大学", "民族学院"],
        "军事": ["陆军工程大学", "海军工程大学", "空军工程大学"],
    }

    # 普通本科批次
    NORMAL_TYPES = ["理工", "综合", "师范", "医药", "财经", "农林", "政法", "语言", "艺术"]

    generated = []
    rank_counter = len(base_schools) + 1

    for city, province in CITIES:
        # 每个城市生成 15-30 所学校
        n_schools = random.randint(15, 30)
        for _ in range(n_schools):
            school_type = random.choice(NORMAL_TYPES)
            suffixes = TYPE_TEMPLATES[school_type]
            suffix = random.choice(suffixes)

            # 避免与已有学校重名
            name = f"{city}{suffix}"
            attempt = 0
            while name in existing_names:
                attempt += 1
                if attempt == 1:
                    name = f"{city}第{random.choice(['一', '二', '三'])}{suffix}"
                elif attempt == 2:
                    name = f"{city}{random.choice(['东', '西', '南', '北'])}{suffix}"
                else:
                    ordinal = random.choice(["一", "二", "三"])
                    suffix_kind = random.choice(["院", "校"])
                    name = f"{city}{school_type}{ordinal}{suffix_kind}"
                if attempt > 5:
                    break

            if name in existing_names:
                continue

            existing_names.add(name)
            generated.append(
                {
                    "name": name,
                    "province": province,
                    "city": city,
                    "level": "普通",
                    "school_type": school_type,
                    "ranking": rank_counter,
                }
            )
            rank_counter += 1

    # 合并所有学校
    all_schools = base_schools + generated
    for s in all_schools:
        s["is_985"] = s["level"] == "985"
        s["is_211"] = s["level"] in ("985", "211")
        s["is_double_first_class"] = s["level"] in ("985", "211", "双一流")
        s["website"] = ""
        s["description"] = ""
    return all_schools


def build_admission_scores(schools):
    """为每所学校生成 3 年 × 多省份的分数线数据"""
    import random

    random.seed(42)

    provinces = [
        "北京",
        "天津",
        "上海",
        "重庆",
        "河北",
        "山西",
        "辽宁",
        "吉林",
        "黑龙江",
        "江苏",
        "浙江",
        "安徽",
        "福建",
        "江西",
        "山东",
        "河南",
        "湖北",
        "湖南",
        "广东",
        "海南",
        "四川",
        "贵州",
        "云南",
        "陕西",
        "甘肃",
        "青海",
        "内蒙古",
        "广西",
        "西藏",
        "宁夏",
        "新疆",
    ]

    # 基础分数线（按学校层次）
    base_scores = {"985": 620, "211": 580, "双一流": 560, "普通": 500}

    scores = []
    for school in schools:
        base = base_scores.get(school["level"], 500)
        # 每校随机选 5-10 个省份
        n_provinces = random.randint(5, min(10, len(provinces)))
        selected = random.sample(provinces, n_provinces)

        for province in selected:
            for year in [2023, 2024, 2025]:
                # 省份间分差 + 年份波动
                province_offset = hash(province) % 30 - 15
                year_offset = (year - 2024) * 5
                noise = random.randint(-10, 10)

                min_score = base + province_offset + year_offset + noise
                max_score = min_score + random.randint(20, 60)
                avg_score = (min_score + max_score) // 2

                scores.append(
                    {
                        "school_name": school["name"],
                        "province": province,
                        "year": year,
                        "subject_type": random.choice(["理科", "文科"]),
                        "batch": "本科一批",
                        "min_score": min_score,
                        "max_score": max_score,
                        "avg_score": avg_score,
                        "min_rank": random.randint(500, 50000),
                    }
                )

    return scores


if __name__ == "__main__":
    schools = build_schools()
    scores = build_admission_scores(schools)

    # 写入 JSON
    out_dir = os.path.dirname(os.path.abspath(__file__))

    with open(os.path.join(out_dir, "seed_schools_full.json"), "w", encoding="utf-8") as f:
        json.dump(schools, f, ensure_ascii=False, indent=2)
    print(f"学校数据: {len(schools)} 所")

    with open(os.path.join(out_dir, "seed_scores_full.json"), "w", encoding="utf-8") as f:
        json.dump(scores, f, ensure_ascii=False, indent=2)
    print(f"分数线数据: {len(scores)} 条")
