"""Contracts for auditable real admission data pilots."""

from backend.real_data.adapter import (
    AdmissionQuery,
    AdmissionQueryResult,
    ApprovalRequiredError,
    query_admission_records_from_approval,
    query_admission_records_from_manifest,
    query_admission_records_from_staging,
)
from backend.real_data.approval import (
    ManualApprovalArtifactPayload,
    ManualApprovalChecklist,
    ManualApprovalReadError,
    ManualApprovalWriteError,
    load_manual_approval_artifact,
    write_manual_approval_artifact,
)
from backend.real_data.bundle import (
    ReviewedAdmissionPilotBundleResult,
    run_reviewed_admission_pilot_bundle_from_artifact,
)
from backend.real_data.contracts import (
    AgentCitationMetadata,
    CanonicalAdmissionCandidate,
    QualityReport,
    build_citation_metadata,
    run_quality_gate,
)
from backend.real_data.manifest import (
    StagingManifestEntry,
    StagingManifestPayload,
    StagingManifestReadError,
    StagingManifestWriteError,
    iter_manifest_artifact_paths,
    load_staging_manifest,
    write_staging_manifest,
)
from backend.real_data.parser import (
    AdmissionParseResult,
    AdmissionSchemaReport,
    RawAdmissionRow,
    assess_raw_admission_schema,
    build_raw_admission_row,
    extract_raw_admission_rows_from_xls,
    normalize_raw_rows,
)
from backend.real_data.pilot import (
    ReviewedAdmissionPilotResult,
    ReviewedRawRowsArtifact,
    ReviewedRawRowsArtifactReadError,
    ReviewedRawRowsPayload,
    load_reviewed_raw_rows_artifact,
    run_reviewed_admission_pilot,
    run_reviewed_admission_pilot_from_artifact,
    write_reviewed_raw_rows_artifact,
)
from backend.real_data.source_registry import (
    HENAN_2025_UNDERGRAD_PARALLEL_PAGE,
    SHANDONG_2025_REGULAR_BATCH_1_PAGE,
    SourcePage,
    SourceSnapshot,
    build_manual_snapshot,
    build_snapshot,
)
from backend.real_data.staging import (
    AdmissionCitationRecord,
    StagingArtifact,
    StagingArtifactPayload,
    StagingArtifactReadError,
    StagingWriteBlockedError,
    load_admission_staging_artifact,
    project_admission_citation_records,
    write_admission_staging_artifact,
)

__all__ = [
    "AdmissionQuery",
    "AdmissionQueryResult",
    "AdmissionCitationRecord",
    "AgentCitationMetadata",
    "AdmissionParseResult",
    "AdmissionSchemaReport",
    "ApprovalRequiredError",
    "CanonicalAdmissionCandidate",
    "ManualApprovalArtifactPayload",
    "ManualApprovalChecklist",
    "ManualApprovalReadError",
    "ManualApprovalWriteError",
    "QualityReport",
    "RawAdmissionRow",
    "ReviewedAdmissionPilotBundleResult",
    "ReviewedAdmissionPilotResult",
    "ReviewedRawRowsArtifact",
    "ReviewedRawRowsArtifactReadError",
    "ReviewedRawRowsPayload",
    "HENAN_2025_UNDERGRAD_PARALLEL_PAGE",
    "SHANDONG_2025_REGULAR_BATCH_1_PAGE",
    "SourcePage",
    "SourceSnapshot",
    "StagingArtifact",
    "StagingArtifactPayload",
    "StagingArtifactReadError",
    "StagingManifestEntry",
    "StagingManifestPayload",
    "StagingManifestReadError",
    "StagingManifestWriteError",
    "StagingWriteBlockedError",
    "assess_raw_admission_schema",
    "build_citation_metadata",
    "build_manual_snapshot",
    "build_raw_admission_row",
    "build_snapshot",
    "extract_raw_admission_rows_from_xls",
    "load_admission_staging_artifact",
    "load_manual_approval_artifact",
    "load_reviewed_raw_rows_artifact",
    "load_staging_manifest",
    "normalize_raw_rows",
    "project_admission_citation_records",
    "iter_manifest_artifact_paths",
    "query_admission_records_from_approval",
    "query_admission_records_from_manifest",
    "query_admission_records_from_staging",
    "run_quality_gate",
    "run_reviewed_admission_pilot_bundle_from_artifact",
    "run_reviewed_admission_pilot",
    "run_reviewed_admission_pilot_from_artifact",
    "write_reviewed_raw_rows_artifact",
    "write_admission_staging_artifact",
    "write_manual_approval_artifact",
    "write_staging_manifest",
]
